image: Visual Studio 2017
version: '4.0.0.{build}'
configuration: Release
platform: x64
branches:
    only:
        - port64

environment:
    matrix:
        - PYTHON: "C:\\Python35-x64"

install:
    - cmd: set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
    - git submodule update --init --recursive

before_build:
    - cmd: tools\\build_boost.bat

build:
    project: JContainers.sln

after_build:
    - cmd: python tools\\install.py x64\\Release

test_script:
    - cmd: python tools\\test.py x64\\Release\\Data\\SKSE\\Plugins\\JContainers64.dll

artifacts:
    - path: dist\*
      name: jcdistro
